services:
  db:
    container_name: postgres_db
    image: postgres:17.4
    restart: unless-stopped
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    ports: 
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_password
      - db_name
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $(cat /run/secrets/db_name) -U $(cat /run/secrets/db_user)"]
      interval: 5s
      timeout: 5s
      retries: 1

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_name:
    file: ./secrets/db_name.txt

volumes:
  postgres-data:
